#!/bin/bash

# Run tests before committing
npm test

# Run linting before committing
npm run lint

# Run build before committing
npm run build

# If any of the above commands fail, the commit will be aborted
